### PR TITLE
beautify list of missing fragments on raise

### PR DESCRIPTION
**Pull request by techgaun**
This PR joins the list of missing fragments so it looks better on raise message.

### CODE REVIEW

**Review by uesteibar — COMMENTED** [review]
Hey thanks for this @techgaun! definitely makes it a lot nicer to look at 😺 

Could we additionally add a test for this? It should be good enough if we used [`assert_raise/3`](https://hexdocs.pm/ex_unit/ExUnit.Assertions.html#assert_raise/3) instead of `assert_raise/2` in [this test](https://github.com/uesteibar/neuron/blob/master/test/neuron/fragment_test.exs#L65-L69) and pass the expected message.

After that this should be good to go and with a better test coverage than before 😃🎉

**Comment by Ninigi** [comment]
Nice addition, thanks for that! I have seen this error a few times and it's not easy to read :smile: 

I guess this goes beyond the scope of this PR, but would it be possible to raise a dedicated error `MissingFragmentsError`, instead of a simple runtime error, so you can catch this specific error and react accordingly (i.e. log additional information)?

Edit: I can make that PR, just wondering if you would be interested @uesteibar

**Comment by uesteibar** [comment]
@Ninigi 100% in for that, feel free to go for it. Anything that makes it easier to spot issues is more than welcome :)

**Comment by techgaun** [comment]
@uesteibar @Ninigi looks like we have a consensus here. I threw the quickest solution but  I like the idea of `MissingFragmentsError`. In that case, looks like we don't have to have this PR open.

@Ninigi let me know if you're doing it or I could do that update as well

**Comment by uesteibar** [comment]
Hi @Ninigi! Can you confirm if you'll take care of this please? otherwise either @techgaun and I can go for it 😃

**Pull request closed without merging**
