### PR TITLE
Fix/dialyzer syntax

### LINKED ISSUE #50: @specs broken or missing values
`Neuron.query/3` defines the return here https://github.com/uesteibar/neuron/blob/master/lib/neuron.ex#L90 but the actual return can include `{:error, HTTPoison.Error.t()}` as returned from https://github.com/uesteibar/neuron/blob/master/lib/neuron/response.ex#L28 .

This breaks our code when trying to handle things like `{:error, %HTTPoison.Error{reason: :timeout}}`

### PR DESCRIPTION
**Pull request by hez**
Fixes a couple broken specs and adds the `HTTPoison.Error.t()` to the `Neuron.query/3` return def.

Also added dialyxir dependency for nicer dialyzer errors.

fixes: https://github.com/uesteibar/neuron/issues/50

### CODE REVIEW

**Comment by uesteibar** [comment]
Hey thanks for taking care of it yourself @hez! ❤️ 

Do you think we could add another step to the [travis build](https://github.com/uesteibar/neuron/blob/master/.travis.yml) to run dialyxir? It seems to be straightforward (explained [here](https://github.com/jeremyjh/dialyxir#continuous-integration) for travis) and it would be a great improvement.

If you could make all this PR into two commits that follow the [contributing guidelines](https://github.com/uesteibar/neuron#contributing), one for fixing the type annotation and another one for adding dialyxir and fixing the types, that would be awesome too 🦄

**Comment by hez** [comment]
@uesteibar totally! We do it with Travis on our projects, the most important part is to get it caching the plts (or you'll drag their servers to halt). If I get a couple I'll add it to a new ~this~ PR.

**Comment by hez** [comment]
@uesteibar I pushed up this commit in another branch https://github.com/uesteibar/neuron/commit/8a557a72d9d1af71a215dfb3ee25bf1bef99c3d5 but was lazy and didn't want to deal with the conflict/resolution in mix.* so its built on this branch. I will create a PR once this has been merged.

**Comment by uesteibar** [comment]
Great job, thank you! ❤️ 🎉

> I will create a PR once this has been merged

that sounds great, please go ahead!

**Pull request merged**
