### PR TITLE
feat(json): Changed default JSON library to Jason and added config se…

### PR DESCRIPTION
**Pull request by ekstrom**
…tting for customizing which JSON library to use

### CODE REVIEW

**Comment by uesteibar** [comment]
HI there @ekstrom!! Thanks for taking the time to put this together ❤️ Could you explain a little bit what the motivation behind this change is and what problem you wanted to solve?

**Comment by ekstrom** [comment]
Motivation for changing the default JSON library to Jason:
1. Performance is better with Jason. See benchmarks: https://github.com/michalmuskala/jason#Benchmarks
2. Other parts of the Elixir community (Phoenix, Ecto) are moving/have moved towards using Jason as default. Applications will not need to include both Poison and Jason deps.

Motivation for making the JSON library customizable:
1. There is a risk that existing code may break when default JSON library is changed. The consumer will be able to choose which library to use.

**Comment by uesteibar** [comment]
that sounds perfect! could we add a test where we use `Poison` as well to make sure we don't break compatibility? other than that this looks great 😃

**Comment by ekstrom** [comment]
Good point. All tests in neuron_test.exs and response_test.exs now run with both Jason and Poison.

**Comment by uesteibar** [comment]
Great job, thank you! ❤️ 🎉

**Comment by uesteibar** [comment]
released on [v3.0.0](https://github.com/uesteibar/neuron/releases/tag/v3.0.0)

**Pull request merged**
